version: "3"
services:
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    env_file: 
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}


  redis:
    image: redis
    restart: always
    container_name: redis


  app:
    container_name: gaigelapp
    restart: always
    build: .
    links:
      - mongodb
      - redis
    depends_on:
      - mongodb
      - redis
    env_file: 
      - .env
    ports:
      - "80:80"
    


  